FROM jenkins/jenkins:2.555.1

USER root

RUN apt-get update && apt-get install -y python3 python3-pip curl
RUN ln -s /usr/bin/python3 /usr/bin/python

# Установка pip без ошибки externally-managed-environment
RUN pip3 install --upgrade pip --break-system-packages

USER jenkins